-- since i m thinking about adding tags later on, i have had 20 seeds generated on the topic of motorcycles for now

INSERT INTO `posts` (`z_user_id`, `language`, `title`, `subtitle`, `content`, `is_published`, `published_at`) VALUES
-- User 1 (13 Beiträge: 1x en, 12x de)
(1, 'en', 'Route 66 on two wheels', 'The ultimate road trip experience', '<p>Multiple lines of text that form the lede, informing new readers quickly and efficiently about the sheer freedom of riding across the USA on a classic cruiser.</p>', 1, '2023-12-25 10:00:00'),
(1, 'de', 'Die neue Ducati Panigale im Test', 'Pures Adrenalin auf der Rennstrecke', '<p>Ich bin bereit für den weniger befahrenen Weg. Bereits den Staub abklopfen. Ja, du hast Glück, wenn du auf dem Track bist. Ich pflegte mir auf die Zunge zu beißen und den Atem anzuhalten bei der Beschleunigung.</p><p>Schnell zu einem <strong>Blitz</strong> heranwachsen. Sei vorsichtig, diese Maschine verzeiht keine Fehler in der Kurve.</p><p>Das ist transzendent, auf einer anderen Ebene, das Handling ist einfach ein absoluter Traum für jeden Sportfahrer.</p>', 1, '2023-12-23 14:30:00'),
(1, 'de', 'Die besten Alpenpässe für Biker', 'Kurven ohne Ende', '<p>Von München bis zum Gardasee. Ja, diese Route bringt dich zur Utopie. Ich fahre wie auf Wolken. Die Kehren des Stilfser Jochs verlangen dir alles ab, aber die Aussicht entschädigt für die Mühe.</p><ul><li>Stelle sicher, dass deine Bremsbeläge noch gut sind.</li><li>Die Reifen sollten ausreichend Profil haben.</li><li>Packe warme Kleidung ein, oben wird es schnell kalt.</li></ul><p>Brauchst dich nicht zu entschuldigen, wenn du langsam machst. Es geht um den Genuss, nicht um Bestzeiten. Die Natur hier ist einfach <em>übernatürlich</em>.</p>', 1, '2023-12-14 09:15:00'),
(1, 'de', 'Kaufberatung: Der richtige Helm', NULL, '<p>Ein guter Helm rettet Leben. Er sollte niemals drücken, sondern exakt sitzen und auch bei hohen Geschwindigkeiten nicht wackeln.</p><p>Einige der besten Marken bieten Carbon-Schalen, gute Belüftungssysteme und Pinlock-Visiere gegen Beschlagen. Wenn du in 5 Jahren noch lebst, wirst du dir selbst für die Investition danken.</p>', 1, '2023-11-05 11:20:00'),
(1, 'de', 'Warum wir Naked Bikes lieben', 'Puristisch und direkt', '<p>Die Motorradwelt hat sich über die Jahre massiv weiterentwickelt. Aber der Trend geht zurück zum Wesentlichen: Ein dicker Motor, ein Lenker, keine Verkleidung.</p><p>Die aufrechte Sitzposition macht das Fahren extrem angenehm. Man spürt den Fahrtwind und die direkte Verbindung zur Straße viel intensiver als auf einem Tourer.</p>', 1, '2023-10-18 16:45:00'),
(1, 'de', 'Entwurf: Mein Umbauprojekt', 'Von Schrott zum Cafe Racer', '<p>Dieser Text ist noch nicht fertig. Die Teile für den Heckumbau sind noch auf dem Postweg.</p>', 0, NULL),
(1, 'de', 'Kettenpflege richtig gemacht', NULL, '<p>Die Kette ist das Herzstück des Antriebs, aber sie wird oft vernachlässigt. Eine gut geschmierte Kette hält fast doppelt so lange.</p><ul><li>Reinige die Kette alle 1000 Kilometer.</li><li>Nutze hochwertiges Kettenspray.</li><li>Vergiss nicht, die Kettenspannung regelmäßig zu prüfen.</li></ul>', 1, '2023-09-12 08:30:00'),
(1, 'de', 'Elektromotorräder im Vormarsch', 'Eine leise Revolution', '<p>Die Drehmomententfaltung von Elektromotorrädern ist gigantisch. Kein Schalten, nur reiner, sofortiger Schub von Null auf Hundert.</p><p>Vergiss nicht die Reichweitendebatte. Für die Hausstrecke reicht es dicke, für die Weltreise wird das Ladenetzwerk immer besser.</p>', 1, '2023-08-22 13:00:00'),
(1, 'de', 'Motorrad einwintern', NULL, '<p>Batterie raus, Tank voll, Reifendruck hoch. Es gibt viele Methoden, aber am Ende zählt nur, dass das Bike trocken steht.</p><p>Decke dein Motorrad gut ab und nutze bei Bedarf ein Batterie-Erhaltungsgerät.</p>', 1, '2023-07-15 10:10:00'),
(1, 'de', 'Kurventraining für Anfänger', 'Blickführung ist alles', '<p>Motorräder fahren dorthin, wo du hinschaust. Die Grundlagen der Fahrphysik bleiben. Wer die Blickführung beherrscht, fährt sicherer und schneller.</p>', 1, '2023-06-30 18:00:00'),
(1, 'de', 'Kurventraining Teil 2', NULL, '<p>Drücken oder Legen? Beide Techniken haben ihre Daseinsberechtigung. Auf engen Pässen drückst du, in schnellen Kurven legst du dich mit in die Kurve.</p>', 1, '2023-05-12 09:45:00'),
(1, 'de', 'Gepäcksysteme im Vergleich', 'Koffer oder Rolle?', '<p>Ich bin komplett auf Soft-Luggage umgestiegen. Die Systeme sind einfach zu gut und brechen bei einem Umfaller nicht so schnell ab wie Aluminiumkoffer.</p>', 1, '2023-04-01 14:20:00'),
(1, 'de', 'Entwurf: Reifendruck', NULL, '<p>Noch in Bearbeitung. Messwerte fehlen.</p>', 0, NULL),

-- User 2 (3 Beiträge)
(2, 'de', 'Ratbike-Kultur', 'Je rostiger, desto besser', '<p>Ein schönes Bike ist langweilig, wenn man sich nicht traut, es im Regen zu fahren. Rost, Tape und Kabelbinder sind deine besten Freunde.</p><p>Lass dem Bike seinen Charakter. Nicht alles muss auf Hochglanz poliert sein.</p>', 1, '2023-11-20 09:00:00'),
(2, 'en', 'Understanding V-Twins', 'The heartbeat of a cruiser', '<p>Engine layout is often overlooked but it is 90% of a bike''s character. Choosing a big displacement V-Twin gives you that low-end torque rumble.</p>', 1, '2023-10-10 11:30:00'),
(2, 'de', 'Sicherheitstraining lohnt sich', NULL, '<p>ABS schafft Vertrauen, Traktionskontrolle rettet im Regen. Kenne die Grenzen deines Bikes und buche zu Beginn der Saison ein Fahrsicherheitstraining.</p>', 1, '2023-09-05 15:15:00'),

-- User 3 (2 Beiträge)
(3, 'de', 'Offroad für Straßenfahrer', 'Abseits des Asphalts', '<p>Nutzt die Fußrasten. Es gibt keine Ausrede mehr. Wenn du auf Schotter stehst, hast du viel mehr Kontrolle über dein Adventure-Bike.</p>', 1, '2023-08-11 08:45:00'),
(3, 'de', 'Erste Hilfe beim Motorradunfall', NULL, '<p>Helm ab oder drauf lassen? Frische dein Wissen auf. Ein Erste-Hilfe-Set unterm Sitz <strong>muss</strong> bei jeder Tour dabei sein.</p>', 1, '2023-07-02 12:00:00'),

-- User 4 (2 Beiträge)
(4, 'en', 'My first 1000 miles', 'Review of my starter bike', '<p>Just finished my break-in period on this awesome lightweight twin. The handling is really clean and forgiving for beginners.</p>', 1, '2023-06-15 10:00:00'),
(4, 'de', 'Der perfekte Chopper-Sitz', 'Für lange Autobahnetappen', '<p>Vergiss die harten Custom-Sitze. Ein gut gepolsterter Solo-Sattel mit Gel-Einlage ändert alles auf langen Touren.</p><ul><li>Achte auf eine wasserabweisende Oberfläche.</li><li>Eine kleine Rückenlehne entlastet die Lendenwirbelsäule enorm.</li></ul>', 1, '2023-05-20 07:30:00');